[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "seleniumuser"
version = "0.0.4"
requires-python = ">=3.10"
dependencies = ["selenium >= 4.2.0",
                "timer",
                "useragent"]